{{- if eq .Values.global.environment "staging" }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-monitoring-infra-staging-grafana
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin
{{- end }}